version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/repo

jobs:
  type-check:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run type-check

workflows:
  version: 2
  check-and-deploy:
    jobs:
      - type-check
